### ISSUE TITLE
The Control type could have a .fail method

### ISSUE THREAD

**Issue by sz-piotr** [earl-js/earl#100]
Sometimes you want to fail unconditionally, e.g. because of some runtime condition not being met for successful execution.

**Comment by krzkaczor** [comment]
I used to throw `EarlConfigurationError` in such cases:

```
if (ctrl.isNegated) {
  throw new EarlConfigurationError("toMatchSnapshot can't be negated")
}
```

Do you think we still need another mechanism for that? What would be signature of `fail`?

**Comment by sz-piotr** [comment]
Here are some of the use cases:
1. You want to fail unconditionally, e.g. `toEqualInteger(value: number)` will use `ctrl.fail` after `Number.isInteger`
2. Your code branches depending on the negation e.g.
<img width="830" alt="Screenshot 2020-12-11 at 17 29 36" src="https://user-images.githubusercontent.com/17070569/101928887-72344380-3bd6-11eb-9102-4809df6d8454.png">

The signature should be the same as `assert`, but `success`, and `negatedReason` will be removed.
