### ISSUE TITLE
RFC: Function Mocks

### ISSUE THREAD

**Issue by krzkaczor** [earl-js/earl#12]
This issue facilitates discussions about builtin function mocks design. First of all, we believe that using mocks is so common that making them part of the library is a sane thing to do.

## Sinon’s Spy
```js
const spy = sinon.spy(() => 5)

// and for asserts with chai-sinon:
expect(mySpy).to.have.been.calledWith("foo");
```

What I don’t like about this design is that it doesn’t have support for easy creation of a spy that returns different values for different calls. 

Another thing is that I always felt like there is way too many sinon-spy matchers but some really useful were [missing]( [https://github.com/sinonjs/sinon/pull/1686](https://github.com/sinonjs/sinon/pull/1686) ).

## Jest’s fn.mock()
```js
const mock = jest.fn(x => 42 + x)
expect(mockFunc).toHaveBeenCalledWith(arg1, arg2);
```

What I like about its design:
* clear design of `.mock` property exposing all the details - makes it possible to write custom expectations by hand,
* Simple helpers to mock different values for different calls:`mock.mockReturnValueOnce(‘x’)` 

## Proposed design
In my experience, I quite often want to return different values for different calls, thus something like Jest’s `mock.mockReturnValueOnce`  (internal queue of returned values) is a must. But this leads us to this weird state where we define returned values in one place but write expectations in a totally another. What if we combined it to something like this:

```js
import {mockFn} from "earl"

const getSizeMock = mockFn([{inputs: [expect.a(Fs), "/path/file.txt"], out: 217}])
```

This mock expects to be called exactly once with a object of type `Fs` and string `/path/file.txt` and returns `217`.

There are at least few cool things about this:
- can throw expectations as soon as unexpected call happens,
- `inputs` is just an array of args so one can use all matchers that would work with `beEqual` (`arrayContaining` if you don't care about details, or `anything` if you really don't care ;d). This API design is just an example, we could utilize helpers like `mockReturnValueOnce` etc but I wanted to present here that I believe that expectations on a mock can be defined as a part of a mock.

Furthermore, it should be possible to do something like `expect(mock).toBeExhusted()` to verify if a mock's internal queue of values to return is empty. So there is no need for something like `expect(mock).toHaveBeenCalledTimes(5)`. 

I imagine that this could be even further simplified with optional integration with test runner (this needs another proposal) which would ensure all mocks created in a testcase are exhausted after each test run.

There is only one thing that I don't like about this idea - implementing `autofix` (for inputs) will be challenging as expectations are defined first and execution happens later.

To clarify, this could be preferred way of using mocks but for sure there are cases where more traditional interface like:

```js
const mock = jest.fn(x => 42 + x)
expect(mockFunc).toHaveBeenCalledTimes(3);
```

is needed and thus should be supported as well. 

Thoughts?

**Comment by sz-piotr** [comment]
How about a system of overrides that allows you to modify things at a later date?

```ts
const callMeMaybe = mockFn().returns(3)
expect(callMeMaybe()).toEqual(3)

callMeMaybe.throwsOnce(new Error('booyah'))
expect(() => callMeMaybe()).toThrow('booyah')
expect(callMeMaybe()).toEqual(3)

callMeMaybe
  .given(1, 3).returns(4)
  .given(2, 4).returns(6)

expect(callMeMaybe()).toEqual(3)
expect(callMeMaybe(1, 3)).toEqual(4)
expect(callMeMaybe(2, 4)).toEqual(6)

callMeMaybe.reset().returns(5)

expect(callMeMaybe()).toEqual(5)

**Comment by quezak** [comment]
#### specifying mock results/expects/etc
:point_up: I very much like the above idea to have a compact way to (1) mock the returned value/error, (2) define the expected call arguments, (3) check the number/arguments of calls, (4) reset/restore the mock at the end of the test. In `jest`, these 4 things have to be done manually, which leads to loads of boilerplate, or writing complicated helper utils that encapsulate them.

The `mock.given(...).returns(...)` syntax looks cool, especially if there was a stackable sequential variant, ie. _the mock should first be once called with `1, 3` and return `2`, then once with `2, 4` and return `6`_ -- this should also fail if it was not called enough times. Example idea:
```typescript
// regular variant
callMeMaybe.calledWith(2).returns(1);
// variant that after the test verifies it indeed was called with the expected args (and/or expected number of times)
callMeMaybe.expectCalledWith(2).returnsOnce(1);
```

#### creating mocks
Explicit `const mock = jest.fn` is only one of the multiple ways to create a mock function. I also extensively use `const spy = jest.spyOn(serviceInstance, 'someMethod')`.

Side wild idea: when using a mock that's a spy of an actual function, it would be nice to have a way to call or wrap the original function.

Another wild idea for creating mocks is mocking whole class instances:
```typescript
const mockSvc = mockInstance(RickRollerService);
// or
const mockSvc = mockInstance(new RickRollerService(...someParams));

// mock a single method
mockSvc.rick.given(1).returnsOnce('pickle')
// or even use matchers in expected args?
mockSvc.roll.given(expect.stringMatching('xyz')).callsOriginal()
// unmocked methods should probably fail the test with a precise message like
// 'unexpected unmocked call to Xxx:yyy <stacktrace>'
// (note "fail the test", not "throw an error", since that could be caught by the tested code)
```

**Comment by krzkaczor** [comment]
I like `given` syntax. But just to clarify, @sz-piotr, in your example above:
```

callMeMaybe
  .given(1, 3).returns(4)
  .given(2, 4).returns(6)

expect(callMeMaybe(2, 4)).toEqual(6)
``` 
throws, right?

Ie. `given` doesn't do "matching of arguments" but simply expects a call with given args.

> The mock.given(...).returns(...) syntax looks cool, especially if there was a stackable sequential variant, ie. the mock should first be once called with 1, 3 and return 2, then once with 2, 4 and return 6 -- this should also fail if it was not called enough times. Example idea:

As mentioned in the first post. I believe mocks should have `isExhausted()` (or `verify`) method which checks if internal queues of inputs and outputs are empty. It's hard for me to understand why I would want to create mock that is not entirely "used" during a test, thus I don't see a valid reason for `expectCalledWith` that you mentioned. I am not sure if I understood your example.

@quezak what you mentioned in `creating mocks` section are great points but I think they belong to a different issue - this one is about function mocks. Wanna scribble something? ;) I was also thinking about how class mocks should look like.

**Comment by sz-piotr** [comment]
@krzkaczor 
> in your example above [...] throws, right?

This example does not throw. My understanding of a mock is: a function which calls you can inspect and does not require an implementation.

The reason for the `given` syntax is to provide an ability to override the return value given some arguments. The real life example would be something like this. You have a class that needs to process employees. This class receives a function that returns salaries for those employees. Instead of passing the real calculation function you pass the mock that returns predefined values.

> It's hard for me to understand why I would want to create mock that is not entirely "used" during a test

Sometimes you create a mock not to spy on it but to mock some part of the system. The simple `mockFn().returns(3)` can never be exhausted, since it has no internal queue.

**Comment by quezak** [comment]
> Sometimes you create a mock not to spy on it but to mock some part of the system. The simple `mockFn().returns(3)` can never be exhausted, since it has no internal queue.

I agree, it's also sometimes useful. But I think we certainly should have a variant that automatically expects the calls to be exhausted directly in the mock given/return declaration. I find it very annoying if I have a dozen mocks and have to manually verify them all -- that's why I proposed to have two ways to declare mock returns.

@sz-piotr your case with two simultaneous non-exhaustive `given` options could be rewritten with `.mockImplementation` and a trivial switch-case-return, so it it worth to have a special syntax for that?

**Comment by krzkaczor** [comment]
> This example does not throw. My understanding of a mock is: a function which calls you can inspect and does not require an implementation.

Okay, I get it, small suggestion: next time you can add some text commentary to your code example to make it clear, especially that you ignored what I proposed in the previous post 😆 

> @sz-piotr your case with two simultaneous non-exhaustive given options could be rewritten with .mockImplementation and a trivial switch-case-return, so it it worth to have a special syntax for that?

Isn't `mockImplementation` jest's thing to override mock created by another module? I think that with what we have discussed now here the better parallel would be a `mockFn` with custom function with switch-case-return, right? Anyway, I think there is still a value in a possiblity to define this case in a more declarative way but I am not sure if this is a right syntax.

To facilitate a little bit our discussion:

1. We have `mockFn` with nice API to define internal return queues WITH possible overrides using `given`. Exactly what @sz-piotr wrote in it's the original post with code sample. 

Features:
- "infinite" returns using `.returns(x)`
- return value queues with `returnOnce(x)`
- support for throw values with `throw`/`throwOnce` 
- override return for specific args `given(args).returnOnce(x)`
- `isExhausted` check
- ability to define mockFn using function: `mockFn(() => 5)`

My opinion: it's good and needed, it's basically an evolution of what `jest` provides. I am just worried that MAYBE "infinite" mocks should be separate from "well defined" mocks.

2. I mentioned that I feel like it's often useful to have "stricter" mocks which would expect calls and throw if something expected is called. This is what I believe what @quezak refers to as well (suggesting `expectCalledWith`).

Maybe it should be a separate type of mock like `strictMockFn`?

I can write a proposal combining all of these ideas so we can talk it through. My gut feeling is that these should be separate kind of mocks rather than one mock with shit load of methods because you wouldn't use them all at once.

**Comment by quezak** [comment]
> Isn't mockImplementation jest's thing to override mock created by another module?

No, it's used to use a more complex function for the mock than a simple `return x`. One of the primary use cases is the one I mentioned, ie. `fn.mockImplementation(arg => arg > 4 ? 2 : 0)`.

**Comment by krzkaczor** [comment]
> fn.mockImplementation(arg => arg > 4 ? 2 : 0).

@quezak how is this different from 
```js
jest.fn((arg => arg > 4 ? 2 : 0)
```

**Comment by quezak** [comment]
> @quezak how is this different from `jest.fn((arg => arg > 4 ? 2 : 0)`

You can't use this with spies / mocks constructed in other ways than a literal fn declaration (e.g. `jest.spyOn(someSvc, 'someMethod').mockImplementation(...)`. Also, it could be useful to have a way to change the mock fn implementation at some point.

**Comment by krzkaczor** [comment]
Yesterday I dove into various mocking frameworks outside JS to steal some good ideas. I even visited PHP land - but I couldn't find any good patterns there 😆

Good news is that it turns out that I didn't invent the concept of [strict/loose mocks](https://github.com/Moq/moq4/wiki/Quickstart#customizing-mock-behavior) 😆 

Here's what I propose:

1) strictMocks (preferred) - functions with a sequence of expected calls and return values specified UPFRONT. They will throw on unexpected calls. They should be always verified by the end of the test (can be done automatically by integration with test runner TBD).

2) mocks (or looseMocks) - functions with dummy implementation/return value, that you can call as many times as you want. They have nice API to override return values for given args. At the end of the test can be verified by set of custom matchers.

(2) is much more similar to what `sinon.spy` / `jest` provides but I feel like (1) is be more useful IRL (at least this is how I often use mocks). I also propose to implement (1) in the first place.

**Comment by krzkaczor** [comment]
@all-contributors please add @sz-piotr for code
