### ISSUE TITLE
Make the "not" modifier stateless?

### ISSUE THREAD

**Issue by rkrupinski** [earl-js/earl#125]
Hello there,

Disclaimer: This did not end up being a PR as the idea discussed here might be considered controversial. Wanted to talk this through first.

Consider the [`not` modifier](https://github.com/earl-js/earl/blob/5b951405f407e9900ef02b174e67177159fdc2f3/packages/earljs/src/Expectation.ts#L38-L46). Current implementation is stateful which makes it vulnerable to stuff like:

```ts
const expectation = expect(2);

expectation.not;

expectation.not.toBeA(Number); // <-- this breaks
```

Two things worth mentioning:
* Of course, storing intermediate stuff in a variable is not the preferred way of constructing assertions.
* Earl kinda [protects itself](https://github.com/earl-js/earl/blob/5b951405f407e9900ef02b174e67177159fdc2f3/packages/earljs/src/Expectation.ts#L39-L41) against being used in such a manner.

The first obvious step on the way to fixing this seems to be moving from getters to function calls. Then instead of `.not` you'd have `.not()`, although:
* Still this falls into the double-negation bucket
* Other assertion libraries seem to have massively adopted the getter pattern (`.not`)

Finally: How about making `.not` actually return a fresh instance, immutably?

Pseudocode:

```ts
get not() {
    return new Expectation(this.actual, !this.isNegated, this.options)
}
```

I admit that I haven't tested that thoroughly, although this simple change seems to:
- fix the example above
- let one store intermediate stuff
- lets one do stuff like `expect(2).not.not.toBeA(Number)` which, although contrived, seems like the behavior I'd actually expect, rather than being able to only negate once.

WDYT?

**Comment by krzkaczor** [comment]
Thanks for this suggestion! I think it's something worth discussing BUT it's kinda hard to hit in real-world scenarios as as you already mentioned "Of course, storing intermediate stuff in a variable is not the preferred way of constructing assertions."

I think it's more elegant to make it stateless, then all constructor arguments can be made `readonly` too. Do you want to create PR for this maybe :->?

**Comment by rkrupinski** [comment]
Yep, will do.

**Comment by krzkaczor** [comment]
Closed by https://github.com/earl-js/earl/pull/126
