### ISSUE TITLE
Feature request: test.each

### ISSUE THREAD

**Issue by paulrberg** [earl-js/earl#133]
Jest offers a [test.each](https://jestjs.io/docs/api#testeachtablename-fn-timeout) functionality, which can take an array of inputs and run the test over them.

I couldn't find a similar feature in Earl.

**Update**: is this something that should be handled by the test runner instead? I found this for Mocha: https://github.com/ryym/mocha-each

**Comment by krzkaczor** [comment]
@paulrberg yes, I believe this should be done by the test runner.
