### ISSUE TITLE
RFC: Plugin system

### ISSUE THREAD

**Issue by krzkaczor** [earl-js/earl#30]
**earl** should support plugins to extend available validators and extractors to specific cases.

## Autoloading

Packages matching naming schema: `earljs-plugin-x` should be autoloaded by **earl** during test initialization (requires test runner integration).

## Type safety

Plugins should use declaration merging to extend `earljs` types. It's not the nicest but I don't see any other way.

## Plugin API

Plugin is a function returning `PluginConfig`. 

```typescript
export interface PluginConfig {
  matchers?: WrapWithName<DynamicMatcher>[]
  validators?: WrapWithName<DynamicValidator<any>>[]
  smartEqRules?: SmartEqRule[]
}
```

Earl can load it via `loadPlugin` function.

Simple plugin package should run `loadPlugin` from their main module so the only thing that users has to do is `import "awesome-earljs-plugin"`.

Added validators and matchers will be automatically attached to earl's `expect` but type info needs to be loaded separately. 

## Implementation

I started implementing it in https://github.com/earl-js/earl/pull/61

**Comment by sz-piotr** [comment]
I don't think the plugins should be asynchronous. If they take no arguments what could they possibly want to load over time?

I am also unsure about autoloading. Why not do what every other plugin based runtime library does and require importing plugins. We don't need `chai.use` but a single import `import 'earl-plugin-something'` should be sufficient.

I also like the idea to extend equality checking because it automatically affects all matchers at once.

**Comment by sz-piotr** [comment]
And btw. If I am a plugin author and I write my plugin in typescript the types will only be used after the plugin is imported because they are not in `@types`

**Comment by krzkaczor** [comment]
Thanks for comments!

> I don't think the plugins should be asynchronous.

I can't agree. Asynchronous code spreads like a virus in JS (colored functions etc). Maybe it's not needed now but who knows about the near future. Making it async from the ground up is easy, but adding it later can be a PITA. Of course, plugins can be `sync` and everything will work.

> I am also unsure about autoloading. Why not do what every other plugin based runtime library does and require importing plugins. We don't need chai.use but a single import import 'earl-plugin-something' should be sufficient.

The reason why I don't like it is that it forces users to create another setup file which should be `--required` by mocha to ensure deterministic load order.

Here we can simplify it and make sure that they are loaded during earl<-> mocha integration which we need for other things anyway.

> And btw. If I am a plugin author and I write my plugin in typescript the types will only be used after the plugin is imported because they are not in @types

Yeah, that's how I would imagine it to work but I need to test it IRL.
