### ISSUE TITLE
Instance matcher and mocks confusion

### ISSUE THREAD

**Issue by Kampfmoehre** [earl-js/earl#36]
Hi, we just tried to move to your library from chai. But we were unable to find a matcher for instances. Is there any such matcher yet? How would I write the following chai expect in earl?

```typescript
const service = new Service();
chai.expect(service).to.be.instanceOf(Service);
```

Same applies for the property matcher. Sometimes we want to check if an object has a property.

```typescript
chai.expect(service).to.have.property("prop");
```

Of course we can circumvent both with equal like

```typescript
const service = new Service();
chai.expect(service instanceof Service).toEqual(true);
chai.expect(Object.prototype.hasOwnProperty.call(service, "prop")).toEqual(true);
```
but the method chai offers seems a little bit easier in my opinion.

Also a Regex matcher would be very nice to have. Currently I have to do something like this:
```typescript
expect(new RegExp(/Error while starting the server.*/).test(msg)).toEqual(true);
```

which works but the error message is very unspecific being only `Error: false not equal to true`.

**Comment by krzkaczor** [comment]
We already support instance matching with:

```typescript
chai.expect(service).to.be.instanceOf(Service);
// becomes
expect(service).toEqual(a(Service))
```

Note: we could simplify such check even further with something like 

```typescript
expect(service).toBeA(Service)
```

but for now we tried to have only one way for doing things (using toEqual). CC: @sz-piotr 

Property matcher is missing indeed. Do you use TypeScript? I didn't found a need to such validator while using TypeScript...

Regex matcher is on it's way ;) It's gonna be available in the next version: https://github.com/krzkaczor/earl/issues/23

**Comment by Kampfmoehre** [comment]
Hi, thx for the quick reply. I just tried your solution but I can't find a method a in your exports. The only exports I have so far are `expect`, `looseMockFn` and `strictMockFn`.

As for the property, here is an example that I stumbled upon currently.

I test a Service that receives a logger and when throwing an error it logs it along with some custom message. For the logger I currently use sinon (couldn't figure out how to use your mocks) like this:

```ts
beforeEach(function () {
  logMock = sinon.stub(logger, "info") as any;
});

it("should report the error, if it fails to start", async function () {
  // Provoke the error, the log line looks like this:
  // this.logger.error({ err }, "Error while starting the server: %s", err.message);
  // Note we use Pino as logger but we have abstracted away it so we can use nearly every logger

  const firstCallArgs = logMock.args[0];
  expect(Object.prototype.hasOwnProperty.call(firstCallArgs[0], "err")).toEqual(true);
  expect((firstCallArgs[0] as Record<string, unknown>).err instanceof Error).toEqual(true);
}
```

**Comment by krzkaczor** [comment]
> The only exports I have so far are expect, looseMockFn and strictMockFn.

ahh sorry, it's `expect.a`. I just woke up :D (i edited my answer).

**Comment by Kampfmoehre** [comment]
No problem. Your library is awesome so far. Testing with typescript always felt a little bit strange. Mocha is difficult when you have multiple different test suites that need different setups (we split our tests in unit, api and integration) and jest always feels way to slow with typescript. We also checked out [alsatian](https://github.com/alsatian-test/alsatian) but it wont work with the many reporters we need.

The biggest obstacle I had with Typescript are mocks. They almost never are typed and/or easy to use at the same time and I am far from understanding how to type them properly with sinon or jest. The best thing that I have found so far is [typemoq](https://github.com/florinn/typemoq) which is inspired by C# and thus I am familiar with it. But in the TS/JS world it seems a little bit too much code for mocking. But it creates correctly typed mocks to use and I don't have to mock everything but only the parts I need.

As far as I have tested your library, I am unsure if and how we use your mocking functionality. In the example above I would need to provide a logger. Most of our code is written with dependency injection so it should be easy to just provide fake instances in tests, right? But often Typescript is making things hard here.

This is how many of our services are written:

```ts
export class Service {
  private readonly logger: LoggerBase;

  constructor(loggerFactory: (name: string|Function) => LoggerBase) {
    this.logger = loggerFactory(this.constructor);
}
```

Now LoggerBase is defined as an interface that has logger function like info, warn, error and so on which each take an object, a string and template params (for the string).
Now since it doesn't create it's own logger, it should be easy to just provide a fake one when instantiating from our test, shouldn't it? Well since all those methods are defined in LoggerBase, typescript wants to have them all, when we create a fake logger:

```ts
new Service(() => ({info: ()=> {}}));
// Typescript throws an error like `Type '{ info: () => void; }' is missing the following properties from type 'LoggerBase': trace, debug, warn, error, fatal`
```

But I only need info for my test. Nearly every mocking framework I tried so far does not handle this very well. I always have to work with casts and loose types or have to silence eslint and typescript. Since most of them are written for JS I guess they don't care much.

What I am really looking for is something like typemoq provides:
```ts
const mock = Mock.of(LoggerBase); // Difficult because LoggerBase is only an interface here so it would be an empty object at runtime
mock.setup("info").withArgs("arg1", AnyString(), ...).return("Whatever"); // ... makes no sense for logger to return something but you'll get the point)

new Service(() => mock.object) // this should have the correct type so ts won't complain and no casts are needed

expect(mock.info).toHaveBeenCalledWith("arg1", "arg2", "...");
// or
mock.verify(); // Throws if not called with the correct arguments

**Comment by krzkaczor** [comment]
> No problem. Your library is awesome so far. 

Thanks! :) 

> The biggest obstacle I had with Typescript are mocks.  

Yeah... currently mocks are minimal in earl exactly because I felt like we need more community feedback. Thanks for mentioning typemoq and writing all your comments.

That being said, currently, in earl we support only functon mocks, and the preferred way of writing mocks are strictMocks where you define calls and return types UP FRONT. As I can see it's not perfect for you since you don't usually care for return types of loggers...

```typescript

const logErrorMock = strictMockFn<any[], void>()
logErrorMock.expectedCall(expect.a(Error)).returns(undefined) // returns undefined because of void return type

// you need to construct dummyLogger manually :(
const logger = {
  info: () => {},
  error: logErrorMock
}

// DO TEST

// you don't need this if you enable test runner integration - all mocks are verified by default
expect(logErrorMock).toBeExhausted()
```

We also have more "standard" mocks like `jest.fn` or `sinon.spy` but they lack documentation for now... we call them looseMocks. 

Thanks again for bringing this up, for sure we will take your notes into account while further improving mocks (obviously it's just a first iteration ;) )

**Comment by krzkaczor** [comment]
> const mock = Mock.of(LoggerBase); // Difficult because LoggerBase is only an interface here so it would be an empty object at runtime

Btw. I think I might have a idea for a solution to make it work. I wanted to implement Mock objects in a way that it takes only type parameter and is es6 proxy where every single call blows if it wasn't properly mocked. But I will dive deeper into `typemoq` and get back to you ;)

**Comment by Kampfmoehre** [comment]
Typemoq allows strict mocks, where every call to non mocked functions will blow up.

As for the logger, it was just an example as I encountered it on the small library I was testing earl on. Of course we also want to mock other things. But we mostly use classes that depend on other classes that are given via dependency injection like shown above or via a DI framework.

**Comment by krzkaczor** [comment]
Mocks were redesigned now. Head to
