### ISSUE TITLE
Use `require('util').inspect.custom` for diffs

### ISSUE THREAD

**Issue by Marik-D** [earl-js/earl#86]
Node uses [`inspect.custom`](https://nodejs.org/api/util.html#util_util_inspect_custom) to let classes define custom formatting when console logged.

It would be nice for earl to also follow that to reduce verbosity if diffs.

**Comment by krzkaczor** [comment]
Earl relies on mocha to print out readable diffs ie. throwing an `AssertionError` with expected and actual objects. Rest is done by a test runner. The only thing that earl does is really replacing matchers with exact values for cleaner diffs. 

I am gonna close this as I don't think we can do anything about it.
