### ISSUE TITLE
toHaveBeenCalledExactlyWith has wrong types

### ISSUE THREAD

**Issue by Marik-D** [earl-js/earl#88]
Currently it's 
```typescript
toHaveBeenCalledExactlyWith(this: Expectation<Mock<any[], any>>, expectedCalls: MockArgs<T>): void;
```
and should be
```typescript
toHaveBeenCalledExactlyWith(this: Expectation<Mock<any[], any>>, expectedCalls: MockArgs<T>[]): void;
```

to account for asserting all of the calls that were performed

**Comment by krzkaczor** [comment]
Right, this seems to be clearly wrong. I will take fix it today.

**Comment by krzkaczor** [comment]
Unless you want to give it a shot @Marik-D :->

**Comment by 96RadhikaJadhav** [comment]
@Marik-D Can I work on it or its already done?

**Comment by krzkaczor** [comment]
Go ahead please.

**Comment by krzkaczor** [comment]
@96RadhikaJadhav are u working on this? If not, tmrw (CET) I will fix it.

**Comment by 96RadhikaJadhav** [comment]
@krzkaczor @Marik-D  I have created a PR. Could you please review it and let me know if any other changes required.

**Comment by krzkaczor** [comment]
Released in: https://github.com/earl-js/earl/releases/tag/earljs%400.1.6
