### ISSUE TITLE
Wrong return type of Control.assert

### ISSUE THREAD

**Issue by sz-piotr** [earl-js/earl#99]
is `void` should be `never`

**Comment by krzkaczor** [comment]
Okay, that's smart. Added it in #101

**Comment by sz-piotr** [comment]
Actually this is not really correct. It may lead to bugs. We should go back to void. Sorry

**Comment by krzkaczor** [comment]
Can u explain when this can happen?

**Comment by sz-piotr** [comment]
Basically if the assertion holds then the function doesn't throw. I made a mistake suggesting previously that it always throws

**Comment by krzkaczor** [comment]
It's true that it doesn't always throw but in fact in all currently created validators calling `assert` is the final statement in a given execution path. In the past there were some bugs when I forgot to `return` directly affect calling it - changing return type to `never` (and tweaking compiler settings) helps with it. 

Your call 🤷
